name: Crowdin - Upload strings
on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: github.repository == 'yamikaitou/YamiCogs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install redgettext==3.4.2
    - name: Generate source files
      run: make gettext
    - name: Upload source files
      uses: crowdin/github-action@v1
      with:
        upload_sources: true
        upload_translations: false
        download_sources: false
        download_translations: false
      env:
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_IDENTIFIER }}